name: CI pipeline

on: 
  push: 
    branches: ["main"]
  
  job: 
    build: 
      runs-on: ubuntu-latest
      
      steps: 
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Set Up Node
          uses: actions/setup-node@v4
          with: 
            node-version: 20
          
        - name: Install Dependencies
          run : npm ci

        - name: Build App
          run : npm run build 

        - name: Build Docker Image
          run : docker build -t tic-tac-toe:ci .


